#!/usr/bin/env ruby
require 'optparse'
require File.expand_path('lib/charted', File.dirname(__FILE__))
require 'dm-migrations'
require 'date'
require 'fileutils'

ENV['CHARTED_CMD'] = '1'

ARGV.options do |o|
  cmd, action = Charted::Command.new, nil
  o.set_summary_indent('  ')
  o.banner = "Usage: #{File.basename($0)} [OPTION]"
  o.on('-d', '--dashboard', 'show dashboard') { action = :dashboard }
  o.on('-h', '--help', 'show this help message') { puts o; exit }
  o.on('-j', '--js', 'output js code') { action = :js }
  o.on('-m', '--migrate', 'migrates database') { cmd.migrate; exit }
  o.on('-s', '--site domain', 'set site') { |site| cmd.site = site }
  o.parse!
  action.nil? ? puts(o) : cmd.send(action)
end
